# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa1b1487202261e20d37288ccbe01b1508f9b44e1ab2f8929c17e7c1308443345720cdcbb6ac0cfdaa6110c8eab5c54995451a0b0e87f360f6572a8e9e6101c6

test:
  secret_key_base: 011cabbf48c67984700f099eeb337a5c2792e4967ce545c0cd83758cd1bce1d85b360b6cf1d231d8c0901e41cff0b37034ea7474d5ea260bbbeee633bca4078f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
